name: Sanity Checks

env:
  TERM: xterm

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  codestyle:
    name: Code Style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make editorconfig-test
